language: cpp

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7
          - gettext
          - autopoint
    env: COMPILER=clang++-3.7

script: ./autogen.sh && ./configure && make
